import Foundation

enum ExtraASEQuestions {
    private struct Scenario {
        let prompt: String
        let correct: String
        let wrong1: String
        let wrong2: String
        let wrong3: String
        let explanation: String
    }

    /// 20 diagnostic concepts per ASE area, each rendered in three shuffled variants.
    /// This gives 60 questions per area before the original seed question is added.
    static let all: [ASEQuestion] = buildBank()

    private static func buildBank() -> [ASEQuestion] {
        var result: [ASEQuestion] = []
        let areas: [(String, [Scenario])] = [
            ("A1", a1), ("A2", a2), ("A3", a3), ("A4", a4),
            ("A5", a5), ("A6", a6), ("A7", a7), ("A8", a8)
        ]

        let leadIns = [
            "",
            "During diagnosis of a second vehicle with the same symptom, ",
            "After verifying the customer concern, "
        ]

        for (area, scenarios) in areas {
            for (scenarioIndex, scenario) in scenarios.enumerated() {
                for variant in 0..<3 {
                    let raw = [scenario.correct, scenario.wrong1, scenario.wrong2, scenario.wrong3]
                    let shift = (scenarioIndex + variant) % 4
                    let rotated = (0..<4).map { raw[($0 + shift) % 4] }
                    let ids = ["A", "B", "C", "D"]
                    let correctIndex = rotated.firstIndex(of: scenario.correct) ?? 0
                    result.append(
                        ASEQuestion(
                            id: String(format: "bank-%@-%02d-%d", area, scenarioIndex + 1, variant + 1),
                            area: area,
                            question: leadIns[variant] + scenario.prompt,
                            choices: zip(ids, rotated).map { ASEChoice(id: $0.0, text: $0.1) },
                            correctID: ids[correctIndex],
                            explanation: scenario.explanation
                        )
                    )
                }
            }
        }
        return result
    }

    private static func s(_ prompt: String, _ correct: String, _ wrong1: String, _ wrong2: String, _ wrong3: String, _ explanation: String) -> Scenario {
        Scenario(prompt: prompt, correct: correct, wrong1: wrong1, wrong2: wrong2, wrong3: wrong3, explanation: explanation)
    }

    private static let a1: [Scenario] = [
        s("A cylinder has low compression and a leakage test sends most air into the crankcase. What is most likely?", "Worn or damaged piston rings", "Burned exhaust valve", "Blown head gasket between cylinders", "Restricted injector", "Air entering the crankcase during a leakage test points to leakage past the piston and rings."),
        s("Oil pressure is low at hot idle but rises near specification with RPM. Which fault is most likely?", "Excessive engine bearing clearance", "Stuck-closed thermostat", "Restricted air filter", "Open injector circuit", "Excessive internal clearance can bleed off oil pressure most noticeably at low pump speed."),
        s("A vacuum gauge is steady except for a sharp drop at regular intervals. What should be suspected first?", "A valve that is not sealing consistently", "Overcharged A/C system", "Weak battery", "Slipping clutch", "A repeating vacuum drop points toward a repeating cylinder sealing event."),
        s("An overhead-cam engine cranks unusually fast with very low compression on all cylinders after cylinder-head work. What should be checked first?", "Camshaft timing", "Fuel pressure", "EVAP purge flow", "Alternator output", "Incorrect cam timing can reduce effective compression across all cylinders."),
        s("Coolant enters one cylinder overnight and the cooling system loses pressure with no external leak. What is the best next test?", "Cylinder leakage or cooling-system pressure test to identify an internal leak", "Wheel alignment", "Charging-system ripple test", "Transmission stall test", "The evidence points to an internal engine-to-coolant sealing problem that should be physically verified."),
        s("A newly rebuilt engine has one cylinder with low compression that improves significantly after adding a small amount of oil. What does that suggest?", "Ring or cylinder-wall sealing loss", "Burned exhaust valve", "Ignition coil failure", "Restricted catalytic converter", "A wet compression increase suggests the oil temporarily improved ring sealing."),
        s("An engine has excessive crankcase pressure, oil leaks, and strong pulsing from the oil-fill opening. Which condition is most likely?", "Excessive blow-by from poor ring sealing", "Low refrigerant charge", "Incorrect toe", "Open purge valve only", "Combustion gases passing the rings create crankcase pressure and blow-by."),
        s("A timing chain rattles on startup and cam/crank correlation is intermittently out of specification. What should be inspected?", "Timing-chain stretch, guides, and tensioner operation", "Brake rotor thickness", "Fuel cap seal", "Wheel bearing preload", "Correlation faults with mechanical startup noise strongly implicate the timing drive."),
        s("One cylinder has low compression, and leakage air is heard clearly at the tailpipe. What is the fault direction?", "Exhaust valve sealing", "Piston rings", "Intake valve sealing", "Fuel injector flow", "Air heard at the tailpipe during leakage testing indicates exhaust-valve leakage."),
        s("One cylinder has low compression, and leakage air is heard clearly at the throttle body. What is the fault direction?", "Intake valve sealing", "Piston rings", "Exhaust valve sealing", "Oil pump output", "Air heard at the intake indicates leakage past the intake valve."),
        s("Milky engine oil and unexplained coolant loss are found after an overheating event. What should be ruled out before further operation?", "Internal coolant-to-oil contamination from head gasket, head, or block damage", "Weak battery", "Worn brake pads", "Incorrect tire pressure", "Coolant in the crankcase can rapidly damage bearings and requires immediate internal-leak diagnosis."),
        s("An engine has a deep knock that increases with load and drops when a suspect cylinder is disabled. What internal condition is likely?", "Connecting-rod bearing damage", "Loose heat shield", "EVAP leak", "Worn wiper linkage", "A load-sensitive deep knock that changes when cylinder load is removed is consistent with rod-bearing clearance."),
        s("Blue smoke is worst after a long deceleration followed by throttle application. What should be considered?", "Valve-stem seal or guide oil leakage", "Low fuel pressure", "Lean injector", "Incorrect caster", "High intake vacuum during deceleration can draw oil past worn valve guides or seals."),
        s("Blue smoke is heavy under acceleration and cylinder leakage is high into the crankcase. What is most likely?", "Worn piston rings or cylinder walls", "Blend-door failure", "Wheel-speed sensor fault", "Stuck thermostat", "Load-related blue smoke combined with crankcase leakage supports ring/cylinder wear."),
        s("A cylinder head is removed after severe overheating. Which inspection is most important before reassembly?", "Check head flatness and pressure-test for cracks", "Balance the tires", "Measure A/C vent temperature", "Program key fobs", "Overheating can warp or crack the head, so sealing surfaces and casting integrity must be verified."),
        s("An engine consumes oil with no external leak and spark plugs show oily deposits. Which mechanical test best helps locate the source?", "Compression and cylinder-leakage testing", "Starter current only", "Wheel alignment", "EVAP smoke test", "Compression and leakage results help distinguish ring and valve sealing problems."),
        s("A freshly assembled engine has no oil pressure immediately after startup. What is the safest response?", "Shut it down immediately and verify oil-pump priming and lubrication-system integrity", "Rev the engine until pressure appears", "Drive it to warm the oil", "Add coolant", "Operating without oil pressure can destroy bearings within seconds."),
        s("A crankshaft end-play measurement is far beyond specification. Which component area requires inspection?", "Thrust bearing surfaces and crankshaft thrust faces", "Catalytic converter", "ABS tone ring", "A/C expansion valve", "Excessive crankshaft axial movement is controlled by the thrust bearing surfaces."),
        s("An engine repeatedly pushes coolant from the reservoir shortly after a cold start, and combustion gas is detected in the cooling system. What is likely?", "Combustion leakage into the cooling system", "Low transmission fluid", "Open wheel-speed sensor", "Weak alternator diode", "Combustion gas present in coolant directly supports a cylinder-to-cooling-system sealing failure."),
        s("A cylinder wall shows a pronounced ridge at the top of ring travel during overhaul. What does this indicate?", "Significant cylinder wear requiring measurement before reuse", "Normal brake wear", "Excessive refrigerant", "Incorrect camber", "A ridge forms where ring travel ends and indicates bore wear that must be measured against service limits.")
    ]

    private static let a2: [Scenario] = [
        s("An automatic transmission has delayed engagement only after sitting overnight. Fluid level is correct. What is a likely cause?", "Internal drainback or an apply-circuit leak", "Stuck-open thermostat", "Weak ignition coil", "Incorrect wheel alignment", "A drained hydraulic circuit can require refill time after a long soak before a clutch applies."),
        s("Commanded gear matches actual gear, but engine RPM flares during torque-converter clutch apply. What should be evaluated?", "Torque-converter clutch slip", "Wheel bearing preload", "Fuel tank venting", "Camber angle", "RPM flare specifically during TCC apply points to converter-clutch holding performance."),
        s("Shifts become harsh when hot and actual line pressure is higher than commanded. What is the best diagnostic direction?", "Pressure-control solenoid and valve-body hydraulic operation", "Engine mounts only", "Battery replacement", "Tire balance", "Actual pressure that disagrees with commanded pressure directs diagnosis toward hydraulic pressure control."),
        s("A transmission slips after service and the installed fluid does not meet specification. What should be done first?", "Correct the fluid type and follow the specified service procedure", "Replace the torque converter", "Replace the TCM", "Perform an alignment", "Fluid friction characteristics directly affect clutch and hydraulic operation."),
        s("A vehicle has no reverse but all forward gears operate normally. Which area should be diagnosed first?", "The reverse apply element and its hydraulic/electrical controls", "Engine cooling fan", "ABS sensor", "EVAP canister", "A fault isolated to reverse points to the element and control path used uniquely for reverse."),
        s("A transmission starts in a high gear, shifts very harshly, and several speed-sensor codes are stored. What mode is likely active?", "Fail-safe or limp-home strategy", "Normal adaptive learning", "Catalyst protection mode", "ABS bleed mode", "Transmission controllers often command a fixed gear and high line pressure when critical inputs are lost."),
        s("Input speed rises sharply during a 2-3 shift while output speed barely changes. What does this indicate?", "A slipping apply element during the shift", "Perfect clutch application", "Wheel imbalance", "Low engine compression", "An input-speed flare during a commanded upshift indicates the oncoming element is not holding correctly."),
        s("The transmission fluid is dark, smells burned, and the pan contains heavy friction material. What is the best conclusion?", "Internal clutch or band damage is likely", "The battery is weak", "The thermostat is stuck open", "The tires need rotation", "Burned fluid and friction debris are direct evidence of internal friction-element distress."),
        s("A shift concern began immediately after battery disconnect, there are no faults, and adaptives were cleared. What should be considered before parts replacement?", "Perform the specified relearn/adaptive drive procedure", "Replace the transmission", "Replace wheel bearings", "Flush the cooling system", "Many electronically controlled transmissions require relearn after adaptive memory is reset."),
        s("A transmission overheats while towing although engine coolant temperature is normal. What should be inspected?", "Transmission cooler flow and load-related slip", "Headlamp aim", "Cabin filter only", "Steering caster", "Transmission heat can result from restricted cooler flow or internal slip under load."),
        s("A transmission range display intermittently shows the wrong gear and a range-sensor circuit code is stored. What should be checked before replacing the transmission?", "Range-sensor data, adjustment, connector, and wiring", "Catalytic converter", "Fuel injectors", "Brake rotors", "The range circuit should be verified because it directly reports selector position to the controller."),
        s("A CVT has engine flare under acceleration and commanded ratio does not match actual ratio. What should be verified next?", "Primary/secondary pressure and ratio control data", "Wheel alignment only", "A/C pressures", "EVAP flow", "Ratio error must be correlated with CVT pressure and control operation before condemning components."),
        s("A transmission engages normally cold but loses drive as fluid temperature rises. Which test is most useful?", "Monitor line pressure and clutch slip while the failure occurs hot", "Measure tire tread depth", "Test horn current", "Inspect cabin filter", "Temperature-dependent hydraulic leakage or friction loss must be captured during the actual failure."),
        s("A harsh downshift occurs only when throttle is closed, and live data shows an implausible accelerator signal. What should be diagnosed?", "The incorrect input signal and its effect on shift scheduling", "Replace all solenoids immediately", "Replace driveshaft", "Replace battery", "Shift strategy depends on inputs; an implausible signal can command an otherwise mechanically sound transmission incorrectly."),
        s("A torque-converter shudder occurs only during lockup and disappears when TCC is commanded off. What has been isolated?", "The converter-clutch apply event", "Engine mount only", "Wheel balance", "Differential backlash", "If the shudder follows TCC command, diagnosis should remain focused on converter-clutch apply and fluid condition."),
        s("A transmission code identifies a pressure-control solenoid circuit open. What should be checked first?", "Solenoid circuit continuity, connector condition, and power/ground as applicable", "Replace the valve body without testing", "Replace the engine", "Rotate tires", "A circuit-open code requires electrical circuit verification before hydraulic parts are condemned."),
        s("After overhaul, a transmission has no movement in any range and the fluid level is correct. Pump pressure is zero. What is the primary direction?", "Verify pump drive, pump assembly, and converter engagement", "Replace ABS module", "Adjust toe", "Test EVAP purge", "Zero pressure with correct fluid means the hydraulic pump is not producing flow."),
        s("A vehicle bangs into gear after a mount replacement, but line pressure and shift data are normal. What should be inspected?", "Drivetrain mount installation and excessive mechanical lash", "Replace the TCM", "Replace oxygen sensors", "Recharge A/C", "Mechanical movement can mimic a harsh engagement even when hydraulic operation is normal."),
        s("A transmission has a gear-ratio code for one gear only. Which comparison is most useful?", "Commanded ratio versus input/output speed ratio during that gear", "Battery voltage at rest only", "Tire pressure", "Coolant freeze point", "Gear-ratio diagnostics depend on comparing expected and measured shaft-speed relationships."),
        s("A pan service reveals a small amount of fine gray paste on the magnet but no chunks or heavy debris. What does this usually indicate?", "Normal wear material unless service information says otherwise", "Catastrophic gear failure", "Blown head gasket", "Failed alternator", "A light coating of fine ferrous paste can be normal; large particles or heavy debris are more concerning.")
    ]

    private static let a3: [Scenario] = [
        s("A manual-transmission vehicle creeps with the clutch pedal fully depressed and reverse grinds. What is most likely?", "The clutch is not fully releasing", "Wheel imbalance", "Open EVAP vent", "Low engine compression", "Creep and reverse grind indicate the input shaft is still being driven with the clutch pedal down."),
        s("A front-wheel-drive vehicle vibrates during acceleration but is smooth on coast. Which component should be inspected closely?", "Inner CV joint", "Cabin air filter", "Outer tie-rod end only", "Thermostat housing", "Inner CV joint wear often produces load-sensitive acceleration vibration."),
        s("A rear-wheel-drive vehicle clunks from drive to reverse and excessive play is measured in the driveshaft before the differential moves. What should be suspected?", "Driveshaft U-joint or slip-joint wear", "Low refrigerant", "Restricted injector", "Faulty oxygen sensor", "Measured lash ahead of the differential directs attention to the driveshaft joints and slip connection."),
        s("A manual transmission jumps out of one gear on deceleration but stays in all others. Linkage is correct. What is most likely?", "Internal wear in that gear's engagement components", "Weak battery", "Bad wheel-speed sensor", "Clogged fuel filter", "A problem isolated to one gear after external adjustment is verified points to internal engagement wear."),
        s("A clicking noise occurs on tight turns under power and is strongest from one front corner. What component is typical?", "Outer CV joint", "Clutch release bearing", "Pinion bearing", "Engine timing chain", "Outer CV joints classically click during high-angle turns under torque."),
        s("A clutch slips in high gear under heavy throttle but does not chatter or drag. What should be evaluated?", "Clutch friction-disc and pressure-plate holding capacity", "Wheel alignment", "Fuel trim", "A/C charge", "Load-dependent engine flare with no matching vehicle acceleration is a clutch holding problem."),
        s("A manual transmission is quiet in neutral with the clutch released but growls when the clutch pedal is depressed. What bearing should be suspected?", "Release bearing", "Rear wheel bearing", "Pilot bearing only during clutch engagement", "Differential side bearing", "The release bearing is loaded when the pedal is depressed."),
        s("A manual transmission growls in neutral with the clutch released and becomes quiet when the pedal is depressed. What area should be considered?", "Input-shaft bearing or transmission input components", "Brake booster", "A/C compressor", "Fuel pump", "With the clutch released, the input shaft spins; depressing the clutch stops or unloads it."),
        s("A vehicle has a vibration at highway speed that changes with road speed but not engine RPM. Driveshaft runout is excessive. What is the likely source?", "Driveshaft condition or balance", "Ignition timing", "Injector pulse width", "Camshaft timing", "Road-speed vibration with measured shaft runout points directly to the driveline."),
        s("A differential howls mainly on acceleration but becomes quieter on coast. What should be inspected?", "Ring-and-pinion contact pattern and bearing preload", "Cabin air filter", "Throttle body", "Heater core", "Drive/coast noise differences are classic clues for gear-mesh setup and bearing issues."),
        s("A differential howls mainly on coast after gear replacement. What is a likely setup issue?", "Incorrect ring-and-pinion contact pattern or pinion depth", "Low battery charge", "Weak fuel pump", "Brake fluid contamination", "Coast-side gear noise after service suggests incorrect gear-mesh setup."),
        s("A four-wheel-drive vehicle binds during tight turns on dry pavement with 4WD locked. What is the best explanation?", "Driveline windup from no center differential action", "Failed oxygen sensor", "Low refrigerant", "Stuck thermostat", "Part-time locked 4WD on high-traction surfaces cannot accommodate front/rear speed differences."),
        s("A transfer case will not shift electronically and scan data shows the selector command changes but encoder position does not. What should be diagnosed?", "Transfer-case shift motor/encoder circuit and mechanism", "Fuel injector balance", "Brake rotor runout", "Camshaft timing", "The command is received, but position feedback fails to change, focusing diagnosis on the shift actuator system."),
        s("A wheel bearing hum changes noticeably when vehicle load shifts left-to-right in gentle highway curves. What does this help identify?", "The loaded wheel bearing as the likely source", "Clutch disc wear", "EVAP leak", "Alternator ripple", "Lateral load changes can increase or decrease noise from a failing hub bearing."),
        s("A solid rear axle has gear oil leaking onto one rear brake assembly. What seal area should be inspected?", "Axle-shaft seal", "Front crank seal", "A/C compressor shaft seal", "Master-cylinder seal", "Oil at the end of a solid axle housing usually indicates axle-shaft seal leakage."),
        s("A clutch pedal stays near the floor and hydraulic fluid is low with visible leakage at the slave cylinder. What repair direction is appropriate?", "Repair the hydraulic leak and bleed the clutch system", "Replace the transmission gears", "Replace wheel bearings", "Program the PCM", "A leaking slave cylinder prevents hydraulic release travel and must be corrected first."),
        s("A clutch chatters only when taking off from a stop and inspection shows oil contamination on the disc. What should be corrected?", "Repair the oil leak and replace contaminated clutch friction components", "Increase tire pressure", "Replace alternator", "Flush brake fluid only", "Oil contamination changes friction unevenly and causes grab-release chatter."),
        s("A propeller shaft U-joint has rust powder around a cap and binds when articulated by hand. What does that indicate?", "A dry or failing U-joint", "Normal operation", "Low coolant", "Incorrect toe", "Rust powder and binding indicate lost lubrication and bearing deterioration."),
        s("A limited-slip differential chatters in slow turns after fluid service. What should be verified first?", "Correct gear oil and required friction modifier", "Battery state of charge", "Ignition coil resistance", "A/C pressure", "Limited-slip clutch packs depend on the specified lubricant/friction characteristics."),
        s("A front axle CV boot is torn and grease has been thrown out, but the joint is not yet noisy. What is the best service decision?", "Service the boot/joint promptly according to condition and procedure before contamination causes wear", "Ignore it until clicking starts", "Replace the engine", "Perform an alignment only", "Loss of grease and contamination can rapidly damage the CV joint even before noise begins.")
    ]

    private static let a4: [Scenario] = [
        s("A vehicle pulls right only while braking. Tire pressures and alignment are correct. What should be checked next?", "Left/right brake force and caliper operation", "EVAP purge flow", "Fuel trim", "Battery state of charge", "A pull that occurs only during braking is more likely a brake-force imbalance than a static alignment issue."),
        s("The steering wheel does not return toward center after a turn and caster is below specification. Which symptom matches?", "Poor steering returnability", "Brake pedal pulsation", "Rich fuel trim", "A/C icing", "Positive caster contributes to directional stability and steering-wheel return."),
        s("A strut vehicle knocks over small bumps and visible movement occurs at the upper mount while steering. What is most likely?", "Worn upper strut mount or bearing", "Wheel imbalance", "Rear axle ratio", "Low fuel pressure", "Visible movement and noise at the upper mount under steering load isolates the mount/bearing assembly."),
        s("One front tire has feathered tread blocks across the surface. Which alignment angle is most directly associated?", "Toe", "Caster only", "Ride height only", "Camber only", "Incorrect toe scrubs the tread laterally and commonly produces feathering."),
        s("A tire shows heavy wear on only the inside shoulder and toe is within specification. Which angle should be checked?", "Camber", "Caster only", "Steering-axis inclination only", "Thrust angle only", "Excessive negative camber commonly concentrates wear on the inside shoulder."),
        s("A vehicle drifts left on a level road and cross-caster is out of specification. Which side typically pulls?", "Toward the side with less positive caster", "Toward the side with more positive caster in every case", "Always toward positive camber only", "Caster cannot influence drift", "A vehicle commonly pulls toward the side with less positive caster."),
        s("A steering wheel shakes at one specific highway speed but is smooth at low speed. What should be checked first?", "Wheel/tire balance and runout", "Engine compression", "EVAP system", "Heater core flow", "Speed-specific steering vibration commonly begins with wheel/tire imbalance or runout."),
        s("Power steering assist is weak only at idle and improves when engine RPM is raised on a hydraulic system. What should be tested?", "Pump pressure/flow and belt drive at idle", "Catalyst efficiency", "Transmission range sensor", "A/C evaporator", "Assist that improves with pump speed points toward hydraulic pump output or drive issues."),
        s("Electric power steering intermittently loses assist and stores a low-voltage code. What should be verified first?", "12-volt power, grounds, and charging-system stability", "Replace steering rack immediately", "Replace all tires", "Recharge A/C", "EPS is highly dependent on stable electrical supply and can disable assist during voltage faults."),
        s("A ball joint shows vertical movement beyond specification when unloaded according to service procedure. What is the correct conclusion?", "The ball joint is worn and should be serviced", "The alternator is weak", "The fuel pump is restricted", "The rotor is warped", "Movement beyond the manufacturer's limit confirms mechanical joint wear."),
        s("A vehicle wanders and needs constant correction. Toe and camber are correct, but front control-arm bushings visibly shift under braking. What is likely?", "Worn control-arm bushings causing dynamic alignment change", "Low refrigerant", "Weak injector", "A/C blend-door fault", "Loose bushings can let alignment angles change while the vehicle is moving."),
        s("A clunk is heard when turning the steering wheel at a stop, and an outer tie-rod stud moves in its socket. What should be repaired?", "The worn tie-rod end", "Fuel filter", "Thermostat", "Rear shock only", "Visible free play in the tie-rod joint directly identifies the steering linkage fault."),
        s("A vehicle sits lower at one corner with no cargo and tire pressures equal. What should be inspected?", "Spring condition and suspension ride-height components", "Oxygen sensors", "Fuel cap", "Starter motor", "Static corner height is controlled by springs and suspension geometry, not engine-control components."),
        s("A shock absorber is leaking heavily and the vehicle continues bouncing after a jounce test. What is the likely effect?", "Poor damping and reduced tire control", "Higher engine compression", "Improved braking", "Lower refrigerant pressure", "A failed damper allows repeated suspension oscillation and reduces tire contact control."),
        s("A steering rack boot is torn and fluid is found inside the boot on a hydraulic rack. What does this suggest?", "An internal rack seal leak", "Normal condensation", "Wheel bearing grease", "Engine oil from the crankcase", "Power-steering fluid inside the rack boot usually indicates internal rack seal leakage."),
        s("A vehicle has torque steer under acceleration and one engine cradle bolt is loose. Why is this relevant?", "Subframe movement can change suspension/steering geometry under load", "It changes refrigerant charge", "It causes catalyst failure", "It increases battery voltage", "A moving cradle changes control-arm and steering mounting positions dynamically."),
        s("After curb impact, steering-axis inclination is out of specification but camber can be adjusted. What should be suspected?", "Bent suspension or steering structural components", "A clogged air filter", "Low transmission fluid", "Weak battery", "SAI is generally not adjustable and abnormal readings often reveal bent parts."),
        s("A vehicle has memory steer after an alignment; the wheel does not smoothly return and strut bearing rotation is notchy. What is likely?", "Binding strut bearing or upper mount", "Fuel injector imbalance", "Brake fluid moisture", "Low A/C charge", "A binding upper bearing prevents free steering rotation and can create memory steer."),
        s("Rear thrust angle is significantly off and the steering wheel is centered only when driving slightly sideways. What should be checked?", "Rear toe/alignment and possible bent rear suspension components", "Engine timing", "Alternator output", "HVAC door operation", "Rear thrust angle determines the direction the rear axle pushes the vehicle."),
        s("A tire has diagonal cupping with worn shocks and wheel balance within limits. What condition can contribute?", "Poor suspension damping", "High fuel pressure", "Rich mixture", "Open thermostat", "Weak damping allows repeated tire hop that contributes to cupped wear patterns.")
    ]

    private static let a5: [Scenario] = [
        s("A brake pedal is firm with the engine off but drops slightly and feels normal when the engine starts. What does this indicate?", "Brake booster assist is operating", "Master cylinder is bypassing", "ABS pump has failed", "There is necessarily air in the system", "A small pedal drop when vacuum assist becomes available is normal booster operation."),
        s("Brake pulsation occurs during high-speed stops and rotor thickness variation is above specification. What repair direction is appropriate?", "Correct the rotor condition and inspect causes of uneven thickness", "Replace the battery", "Adjust caster", "Replace the fuel pump", "Thickness variation changes braking torque as the rotor rotates and causes pedal pulsation."),
        s("One wheel remains applied after pedal release. Opening that caliper bleeder frees it immediately. What does this prove?", "Hydraulic pressure is trapped upstream of the caliper", "Wheel bearing is seized", "Tire is out of balance", "ABS warning lamp is defective", "If opening the bleeder releases the brake, pressure was trapped in the hydraulic circuit."),
        s("ABS activates at 3 mph on dry pavement and one wheel-speed signal drops to zero early. What is the best diagnostic direction?", "Inspect that wheel's sensor, encoder, air gap, and circuit", "Replace master cylinder", "Bleed all brakes first", "Replace all four sensors", "A single implausible low-speed signal should be proven at that wheel."),
        s("A brake pedal slowly sinks while steady pressure is held and no external leaks are visible. What is most likely?", "Internal master-cylinder bypass", "Wheel imbalance", "Low refrigerant", "Open EVAP vent", "A pedal that sinks under steady force without external leakage indicates fluid bypassing internally."),
        s("The brake pedal is spongy after a hydraulic line was opened. What should be done first?", "Bleed the hydraulic system using the specified procedure", "Replace all calipers", "Align the wheels", "Replace alternator", "Compressible air in the hydraulic system commonly causes a spongy pedal after service."),
        s("A vehicle pulls left during braking and the right-front rotor is much cooler than the left after equal stops. What should be suspected?", "Reduced braking force at the right front", "Too much caster on the left", "Rich fuel trim", "Low engine oil", "The cooler rotor indicates that corner is doing less braking work."),
        s("A brake hose is externally intact but the wheel drags after release and the condition improves when the hose is loosened upstream. What can occur internally?", "A collapsed hose can act like a one-way restriction", "Rotor becomes magnetized", "Wheel bearing creates hydraulic pressure", "ABS sensor closes the caliper", "A deteriorated hose liner can trap pressure even when the exterior looks normal."),
        s("Brake fluid is dark and moisture content is above service limit. Why is replacement recommended?", "Moisture lowers boiling point and promotes corrosion", "It increases tire wear", "It raises compression", "It improves ABS response", "Brake fluid absorbs moisture, which lowers boiling point and can corrode hydraulic components."),
        s("A red brake warning lamp stays on and the parking brake is fully released. What should be checked?", "Hydraulic fluid level and brake-system warning inputs", "Catalyst efficiency", "A/C pressure", "Fuel trim", "The red brake lamp can indicate low fluid, pressure imbalance, or parking-brake input."),
        s("Rear drum brakes require excessive pedal travel but hydraulic components are leak-free. What adjustment-related issue can cause this?", "Excessive shoe-to-drum clearance", "Incorrect caster", "Low fuel pressure", "Weak battery", "Too much shoe clearance requires extra fluid displacement before the shoes contact the drum."),
        s("A parking brake will not hold on a grade, but the service brakes work normally. What system should be diagnosed?", "Parking-brake cables, adjustment, and mechanical apply components", "Engine cooling", "Transmission TCC", "EVAP purge", "A normal service brake with poor parking hold isolates the mechanical parking-brake system."),
        s("An ABS wheel-speed sensor produces a clean waveform except for one repeating dropout per wheel revolution. What should be inspected?", "Encoder/tone ring for localized damage or contamination", "Fuel injector", "Thermostat", "A/C clutch", "A dropout at the same rotational position suggests a physical encoder defect."),
        s("The ABS pump runs continuously with the key on because the relay contacts are stuck. What should be addressed?", "Relay/control fault before pump damage occurs", "Wheel alignment", "Fuel cap", "Spark plugs", "Continuous pump operation can overheat the motor and points to the relay/control circuit."),
        s("A vehicle has a hard brake pedal with very little assist and booster vacuum supply is nearly zero. What should be diagnosed first?", "Vacuum source and booster supply circuit", "Rotor thickness", "Wheel balance", "Refrigerant charge", "A vacuum booster cannot provide assist without adequate vacuum supply."),
        s("A hydroboost-equipped vehicle has poor brake assist and power steering is also weak. What shared system should be checked?", "Power-steering/hydraulic pump supply and pressure", "EVAP system", "Catalyst", "Ignition coils", "Hydroboost and steering can share the same hydraulic pump, so simultaneous weakness points to the common supply."),
        s("A rotor has lateral runout above specification shortly after installation. What should be checked before replacing it again?", "Hub face cleanliness, hub runout, and wheel fastener torque", "Fuel pressure", "Battery electrolyte", "Cam timing", "Hub contamination or runout can create installed rotor runout even with a new rotor."),
        s("One brake pad is worn much thinner than its mate in the same floating caliper. What should be inspected?", "Caliper slide pins and piston movement", "A/C blend door", "Fuel injector balance", "Wheel alignment only", "Uneven pad wear in a floating caliper often indicates restricted slide or piston movement."),
        s("Brake pedal pulsation occurs only when ABS is active on loose gravel. Is that necessarily a fault?", "No, pedal feedback can be normal during ABS modulation", "Yes, replace master cylinder", "Yes, replace all rotors", "Yes, disable ABS", "Rapid pressure modulation can be felt in the pedal during normal ABS operation."),
        s("An electronic parking brake service is attempted without placing the system in service mode. What risk exists?", "Actuator or caliper damage and incorrect piston retraction", "Higher engine compression", "A richer mixture", "Lower tire pressure", "Electronic parking brake mechanisms often require a commanded service position before rear brake service.")
    ]

    private static let a6: [Scenario] = [
        s("Battery voltage is 12.6 V at rest, but a 2.1 V drop is measured from the negative post to the engine block while cranking. What is the fault direction?", "Excessive resistance in the ground side of the starting circuit", "Fuel pressure is low", "Alternator is overcharging", "Immobilizer key is necessarily bad", "A large loaded voltage drop on the ground path proves excessive resistance there."),
        s("A CAN network measures about 120 ohms asleep when about 60 ohms is expected. What does this suggest?", "One terminating resistor or its circuit may be open", "Both terminators are shorted together", "Battery is fully charged", "Fuel pump is restricted", "Two 120-ohm terminators in parallel produce about 60 ohms; 120 ohms suggests one is missing."),
        s("Several unrelated 5-volt sensors set circuit-low codes at the same time. What should be checked first?", "The shared 5-volt reference and ground circuits", "Tire pressure", "Cabin filter restriction", "Brake rotor runout", "Simultaneous faults on unrelated sensors often point to a common reference or ground."),
        s("A fuse blows immediately whenever a circuit is powered. What is the safest diagnostic approach?", "Isolate branches and locate the short using a current-limited method", "Install a larger fuse", "Bypass the fuse", "Replace every component", "Current-limited branch isolation protects the harness while locating the short."),
        s("A starter draws very high current and cranks the engine slowly while battery voltage and cables test good. What should be suspected?", "Starter internal drag or excessive mechanical engine load", "Open EVAP vent", "Low A/C charge", "Incorrect toe", "High current with good supply indicates heavy electrical/mechanical load rather than insufficient current delivery."),
        s("Charging voltage is low and alternator output rises when a poor B+ connection is bypassed. What has been proven?", "Excessive resistance in the alternator output path", "Failed battery temperature sensor", "Bad wheel bearing", "Rich fuel mixture", "Restoring output through a bypass proves the original charging path has excessive voltage drop."),
        s("Headlights brighten and dim in rhythm and AC ripple at the battery is excessive. What is likely?", "Alternator diode or rectifier fault", "Fuel injector clog", "Brake caliper drag", "Thermostat stuck open", "Excessive AC ripple is commonly caused by failed alternator rectifier diodes."),
        s("A relay-controlled load works when relay power contacts are jumped, and control-side power is present but the relay never clicks. What should be tested?", "Relay coil ground/control and relay coil integrity", "Replace the load", "Replace battery only", "Align wheels", "The load circuit works; diagnosis should focus on the relay control side and coil."),
        s("A parasitic draw remains high after modules should be asleep. Pulling one fuse drops the draw to normal. What is the next step?", "Identify loads/modules on that fused branch and isolate them", "Replace alternator automatically", "Replace all fuses", "Increase battery size", "The fuse identifies the affected branch; individual loads on that branch must then be isolated."),
        s("A module has correct power but 1.8 V appears between its ground terminal and battery negative under load. What does this indicate?", "Excessive ground-circuit voltage drop", "Normal operation", "Low refrigerant", "Incorrect camber", "Ground voltage should remain very close to battery negative under load."),
        s("A sensor signal is correct at the sensor but distorted at the control module connector. What should be diagnosed?", "Signal-wire integrity, connector resistance, or interference between those points", "Replace sensor immediately", "Replace tires", "Recharge A/C", "A good source signal that changes before the module isolates the problem to the circuit path."),
        s("Two data wires on a CAN network are shorted together and communication is lost. What measurement can help locate the fault with power off?", "Resistance and circuit isolation following network service information", "Fuel pressure", "Compression test", "Brake rotor runout", "Network resistance and branch isolation are standard ways to locate physical bus faults."),
        s("A battery repeatedly goes dead but passes a capacity test and charging output is normal. What should be checked?", "Key-off parasitic current after module sleep", "Camshaft timing", "Wheel alignment", "A/C pressures", "With battery and charging system verified, excessive key-off current becomes a primary suspect."),
        s("A power window works slowly and voltage drop across the switch is 3 V while operating. What does that mean?", "Excessive resistance across the switch", "Motor has perfect supply", "Battery is overcharged", "Window regulator is necessarily broken", "A healthy closed switch should have very little voltage across it under load."),
        s("A ground splice serving several lamps is corroded and multiple lamps glow dimly. What repair is appropriate?", "Restore a clean low-resistance ground connection", "Install higher-wattage bulbs", "Replace alternator only", "Add larger fuses", "A shared high-resistance ground can make multiple loads dim or backfeed."),
        s("A Hall-effect position sensor has correct power and ground but no switching signal while the target moves. What should be verified before replacement?", "Target/air gap and signal circuit, then sensor operation", "Brake fluid", "Fuel cap", "Tire balance", "Hall sensors require correct supply, target geometry, and a functional signal path."),
        s("A PWM-controlled solenoid shows battery voltage on a standard meter even though duty cycle changes on a scope. Why?", "A digital meter may average a pulsed signal and hide switching detail", "The scope is wrong", "The solenoid must be open", "The battery is weak", "PWM diagnosis often requires waveform or duty-cycle measurement rather than only average voltage."),
        s("An incandescent test light causes a low-current module output to shut down. What should be used instead?", "A high-impedance meter or approved low-current test device", "A larger test lamp", "A jumper to battery positive", "A bigger fuse", "Modern low-current module outputs can be overloaded by traditional test lamps."),
        s("A battery has 12.6 V open-circuit but drops below 8 V during a proper load test. What is the conclusion?", "The battery cannot maintain voltage under load", "Alternator is overcharging", "Starter circuit is perfect", "CAN resistance is wrong", "Open-circuit voltage alone does not prove capacity; excessive loaded voltage drop indicates a weak battery."),
        s("A module repeatedly resets when a high-current accessory turns on. What should be captured?", "Module supply and ground voltage during the accessory event", "Tire pressure", "Exhaust backpressure", "A/C vent temperature", "Transient supply or ground disturbances can reset modules and must be measured during the event.")
    ]

    private static let a7: [Scenario] = [
        s("A/C low-side pressure is high and high-side pressure is low while vent air is warm. Compressor command is present. What is most likely?", "Compressor is not producing adequate pressure differential", "System is overcharged", "Condenser airflow is restricted causing very high head pressure", "Heater core is restricted", "High low-side with low high-side means the compressor is not creating the expected pressure difference."),
        s("A/C is cold at highway speed but warm at idle; high-side pressure rises sharply and condenser airflow is weak. What should be inspected first?", "Condenser fan operation and airflow", "Engine compression", "Transmission fluid", "Wheel alignment", "Poor condenser airflow is most critical at idle because ram air is absent."),
        s("Both heater hoses are hot and blower speed is normal, but discharge air stays cold on full heat. What system area is most likely?", "Temperature blend-door or air-mix control", "Refrigerant charge", "Engine oil pressure", "Fuel delivery", "Hot heater hoses show the core has heat, so the air-mix system becomes the primary direction."),
        s("An evaporator freezes after extended operation and vent airflow drops greatly. What should be evaluated?", "Evaporator temperature sensing/control and airflow", "Differential backlash", "Brake fluid moisture", "Battery cable resistance", "Evaporator icing restricts airflow and can result from incorrect temperature control or poor airflow."),
        s("Low side is very low, high side is lower than normal, and the sight/charge data indicate insufficient refrigerant. What condition is likely?", "Low refrigerant charge", "Severely overcharged system", "Blocked heater core", "Stuck blend door", "Low system mass flow commonly produces low suction and lower-than-normal discharge pressure."),
        s("Low side is very low and high side is excessively high with frost near a metering device. What should be suspected?", "Restriction at or near the expansion device", "Weak compressor", "Low engine compression", "Open thermostat", "A restriction starves the evaporator while refrigerant backs up on the high side."),
        s("Both A/C pressures are higher than normal and cooling worsens at idle after too much refrigerant was added. What is likely?", "System overcharge", "Empty system", "Failed heater valve only", "Low battery voltage", "Excess refrigerant reduces condenser capacity and raises operating pressures."),
        s("A blower works only on high speed on a resistor-controlled system. What component should be checked?", "Blower resistor and lower-speed circuit", "A/C compressor clutch", "Heater core", "Refrigerant oil level only", "High speed often bypasses the resistor, so loss of lower speeds points to the resistor circuit."),
        s("Automatic climate control displays the wrong outside temperature and cooling strategy is incorrect. What input should be verified?", "Ambient temperature sensor and circuit", "Transmission output speed", "Brake switch", "Fuel level sensor", "Automatic HVAC control uses ambient temperature as an input to operating strategy."),
        s("A/C clutch does not engage because static refrigerant pressure is below the low-pressure cutoff threshold. What should be done?", "Leak-test and correct refrigerant charge before bypassing controls", "Jump the switch permanently", "Replace compressor automatically", "Increase fuse size", "Low-pressure protection prevents compressor damage when charge is insufficient."),
        s("A/C has a musty odor at startup but cools normally. What area should be inspected?", "Evaporator case drainage and microbial contamination", "Engine bearings", "Rear differential", "ABS module", "Moisture on the evaporator can support odor-causing microbial growth if drainage or drying is poor."),
        s("The blower motor is noisy and airflow is weak; the cabin filter is heavily restricted. What should be corrected first?", "Replace the restricted filter and verify blower airflow", "Recharge refrigerant", "Replace heater core", "Replace compressor", "A blocked filter directly reduces air volume and can increase blower noise/load."),
        s("Heater output is poor at idle but improves with engine RPM, and one heater hose is much cooler than the other. What should be checked?", "Coolant flow through the heater core and cooling-system air/restriction", "Wheel alignment", "A/C refrigerant only", "Battery capacity", "A large hose temperature difference with RPM-sensitive heat points to insufficient coolant flow."),
        s("The heater is cold and both heater hoses remain cool even after the engine reaches normal temperature. What should be diagnosed?", "Coolant flow to the heater circuit and thermostat/cooling-system operation", "Blend door only", "A/C high-side pressure", "Brake fluid", "If neither hose is hot, the heater core is not receiving adequate hot coolant."),
        s("A dual-zone system is cold on the driver's side but warm on the passenger side with correct refrigerant pressures. What is a likely direction?", "Passenger-side blend-door actuator or air-mix fault", "Compressor failure", "Low system charge always", "Condenser fan failure", "Side-to-side temperature difference with normal refrigeration points toward zoned air distribution/control."),
        s("A compressor clutch cycles rapidly and the low side falls below the cycling threshold quickly. What condition should be considered?", "Low refrigerant charge or restricted flow", "Overfilled fuel tank", "Wheel imbalance", "High battery capacity", "Rapid low-pressure cycling commonly results from insufficient refrigerant mass or restricted flow."),
        s("High-side pressure is extreme and low side is also elevated while condenser fan is inoperative. What is the immediate concern?", "Inadequate heat rejection at the condenser", "Low charge", "Evaporator icing", "Heater valve leak only", "Without condenser airflow, refrigerant cannot reject heat and system pressures rise."),
        s("Water leaks onto the passenger floor only when A/C has been operating. What should be inspected?", "Evaporator condensate drain", "Engine head gasket", "Brake hose", "Fuel pressure regulator", "A blocked or disconnected evaporator drain can route condensate into the cabin."),
        s("A heater control valve is commanded closed but hot coolant continues to flow through the core, creating unwanted heat. What should be checked?", "Valve operation and command circuit", "A/C receiver-drier only", "Wheel-speed sensor", "Starter relay", "If coolant flow remains when the valve should close, the valve or its control is suspect."),
        s("After compressor replacement, the system cools poorly and debris is found throughout the refrigerant circuit. What should have been addressed?", "Contamination cleanup and replacement of affected components per service procedure", "Tire rotation", "Battery relearn", "Brake bleeding", "Compressor debris can recirculate and damage the new compressor or restrict the system.")
    ]

    private static let a8: [Scenario] = [
        s("Long-term fuel trim is +22% at idle but near 0% at 2500 rpm with no load. What is most likely?", "A vacuum leak with greatest effect at idle", "Restricted exhaust", "Overcharging alternator", "Slipping clutch", "Unmetered air has its largest percentage effect at low airflow, so trims often improve with RPM."),
        s("A misfire is on cylinder 2. Moving its ignition coil to cylinder 4 moves the misfire to cylinder 4. What has been proven?", "The moved ignition coil is faulty", "Cylinder 2 has low compression", "Fuel pump is weak", "Catalytic converter is restricted", "A fault that follows a component during a controlled swap directly implicates that component."),
        s("Commanded fuel pressure stays high during loaded acceleration but actual pressure falls and the engine goes lean. What should be diagnosed?", "Fuel-delivery ability under load", "Wheel alignment", "A/C blend door", "Brake booster vacuum only", "Actual fuel pressure failing to follow commanded pressure under demand points to supply or pressure control."),
        s("The downstream oxygen sensor closely mirrors the upstream sensor after the catalyst is hot. What does this pattern suggest?", "Low catalyst oxygen-storage efficiency", "Perfect catalyst", "Weak battery", "Stuck thermostat only", "A healthy catalyst dampens downstream switching; close mirroring suggests reduced catalyst efficiency."),
        s("Fuel trims are strongly negative on both banks and fuel pressure is above specification. What should be suspected?", "Excessive fuel pressure or rich fuel delivery", "Large vacuum leak", "Restricted fuel supply", "Low battery voltage only", "Negative fuel trim means the controller is subtracting fuel to correct a rich condition."),
        s("One cylinder misfires at idle; compression and ignition are good, and injector balance shows almost no pressure drop for that cylinder. What is likely?", "Restricted or non-flowing injector", "Worn wheel bearing", "Low A/C charge", "Incorrect toe", "Little pressure drop during balance testing indicates that injector is delivering less fuel."),
        s("An engine lacks power at high load and exhaust backpressure rises far above specification with RPM. What should be suspected?", "Restricted exhaust or catalytic converter", "Vacuum leak only", "Weak battery", "Low tire pressure", "Excessive exhaust backpressure under load can severely restrict engine breathing."),
        s("A MAF-equipped engine goes lean under load, and measured airflow is much lower than expected although intake plumbing is sealed. What should be evaluated?", "MAF sensor accuracy and airflow path", "Brake rotor runout", "A/C blend door", "Wheel alignment", "Underreported airflow can cause inadequate fueling on a MAF-based strategy."),
        s("A crank-no-start has spark and injector pulse, but fuel pressure is zero. What system should be diagnosed next?", "Fuel pump power, ground, command, and delivery", "Wheel bearings", "HVAC controls", "Steering alignment", "With spark and injection command present, zero fuel pressure directly shifts diagnosis to fuel delivery."),
        s("A crank-no-start has fuel pressure but no RPM signal on scan data while cranking. What input should be investigated?", "Crankshaft position signal and circuit", "A/C pressure sensor", "Brake switch", "Fuel level sender", "The controller generally needs a valid crank signal to establish engine speed, ignition, and injection timing."),
        s("An engine pings under load and scan data shows knock retard cannot control the event. What should be checked?", "Fuel quality, combustion temperature, deposits, mixture, and knock-sensor operation", "Wheel alignment", "Cabin filter", "Brake fluid", "Detonation can result from fuel, temperature, mixture, deposits, or knock-control faults."),
        s("A cold engine reports coolant temperature near 250°F before startup. What effect can this have?", "Incorrect fueling and cold-start strategy from a biased ECT signal", "Improved cold enrichment", "Higher tire pressure", "Better A/C cooling", "A falsely hot coolant signal can prevent needed cold enrichment and alter many strategies."),
        s("An upstream oxygen sensor is stuck lean but propane enrichment makes it respond rich immediately. What does this prove?", "The sensor can respond; the engine may actually be lean or the condition is upstream", "The sensor is definitely dead", "The catalyst is definitely melted", "The battery is weak", "A sensor that responds correctly to a known mixture change is capable of reporting mixture."),
        s("A throttle-by-wire vehicle has reduced power and the two accelerator pedal position signals disagree. What should be diagnosed?", "APP sensor correlation, wiring, and reference circuits", "Fuel cap", "Wheel bearing", "A/C charge", "Redundant pedal signals are compared for safety; disagreement can trigger reduced-power mode."),
        s("An engine stalls when coming to a stop and throttle plate deposits are heavy on an electronic throttle system. What should be considered?", "Throttle-body cleaning/relearn according to service procedure", "Replace transmission", "Replace all injectors", "Recharge A/C", "Deposits can reduce effective idle airflow, and some systems require relearn after cleaning."),
        s("A purge valve is stuck open and the engine is rough only after refueling. Why?", "Excess fuel vapor enters the intake when purge should be controlled", "Brake fluid enters the engine", "Battery voltage rises", "Wheel alignment changes", "An uncontrolled purge path can create an overly rich mixture after the canister is loaded with fresh vapor."),
        s("Fuel trim is normal at idle but becomes strongly positive under load while fuel pressure drops. What does that pattern support?", "Insufficient fuel volume or pressure under demand", "Vacuum leak at idle", "Excessive fuel pressure", "Perfect fuel delivery", "A demand-related lean condition with falling pressure points to inadequate fuel supply."),
        s("A misfire occurs only on cold start for a few seconds and one spark plug is unusually clean. Coolant pressure also drops overnight. What should be suspected?", "Small coolant leak into that cylinder", "Overcharged A/C", "Wheel imbalance", "Open brake switch", "Coolant can steam-clean a plug and cause a brief cold-start misfire before clearing."),
        s("An engine has poor acceleration and the throttle opens fully, but calculated load remains low and manifold vacuum stays unusually high. What should be considered?", "Airflow restriction such as a restricted intake or exhaust", "Excessive tire pressure", "Brake fluid moisture", "A/C evaporator icing only", "Low calculated load with high vacuum at wide throttle suggests the engine cannot breathe normally."),
        s("A variable-valve-timing code returns and commanded cam angle changes but actual angle responds slowly. Oil level and viscosity are incorrect. What should be corrected first?", "Engine oil level/condition/viscosity before deeper VVT diagnosis", "Wheel alignment", "Fuel cap", "Brake pad thickness", "VVT actuators depend on proper engine-oil supply and hydraulic response.")
    ]
}

extension AppData {
    var trainingQuestions: [ASEQuestion] {
        aseQuestions + ExtraASEQuestions.all
    }

    /// Builds a different 20-question practice test each time.
    /// Generated questions are grouped by concept so the same concept is not repeated
    /// twice in a single test even though each concept has multiple variants in the bank.
    func practiceTest(area: String, questionCount: Int = 20) -> [ASEQuestion] {
        let pool = trainingQuestions.filter { $0.area == area }
        let grouped = Dictionary(grouping: pool) { question -> String in
            let parts = question.id.split(separator: "-")
            if question.id.hasPrefix("bank-"), parts.count >= 3 {
                return parts.prefix(3).joined(separator: "-")
            }
            return question.id
        }

        var picked = grouped.values.compactMap { $0.randomElement() }.shuffled()
        if picked.count < questionCount {
            let pickedIDs = Set(picked.map(\.id))
            picked += pool.filter { !pickedIDs.contains($0.id) }.shuffled()
        }
        return Array(picked.prefix(min(questionCount, picked.count)))
    }
}
